### ISSUE TITLE
How to convey that you need to transfer money to unlock ungrade

### ISSUE THREAD

**Issue by hancandy** [Putaitu/idle-skat#21]
Miguel thought the 5000 to unlock machines meant money in the company account, could a step by step tutorial work?

- could you force the player to transfer money to personal account early on?
- Maybe a quest? Make a transfer to your personal account (say just 1000 kr.) before you can
  - Change price: Price changing is not essential right at the beginning so we can block this feature
  - Change time : make time go faster, i like this because players should increase time only when they understand the game, and making a transfer show that the player has learned
  - Machines
  - Overdraft
  - Accountant

**Comment by mrzapp** [comment]
Perhaps 💰?
