### ISSUE TITLE
Year end bug

### ISSUE THREAD

**Issue by hancandy** [Putaitu/idle-skat#30]
1. Minor issue: when you click settle, the number in the accounts didn't update, could be confusing
2. Major issue: no more game after year end xDD, no more notification, b-tax...etc. timeline is empty, also the numbers don't seem to reset, it accumulates last year's sales and profit.
* you can still pay VAT, but no reporting

**Comment by mrzapp** [comment]
That was goddamn stupid.

```
if(ConfigService.set('isSetupComplete')) {
     ...
}
```

I used the "set" method instead of "get", resulting in the game starting over every year, but with all VAT 
 and B tax paid :D
